"""What a filled interior actually lays down, measured on the emitted G-code.

Every accept criterion for the Interior feature is a claim about clay: where
the fill sits relative to the wall it welds to, whether a rib has anything
under it, how often the nozzle lifts.  None of those can be settled by reading
the builder — they are settled by running the route Pete runs (mesh -> slice
-> modulate -> finalize -> gcode) and measuring the file that comes out.  So
this module drives the same HTTP endpoints as
:mod:`tests.test_pineapple_crown_sliver` and reuses that module's own G-code
parser rather than writing a second one that would be free to disagree with it.

The two forms are the fixtures the feature was shaped around: ``teapot-lid``,
a shallow closed dome that is filled edge to edge on every layer, for the solid
interior; and ``tall-tumbler``, 39 layers of a gently bellied cylinder, for the
sparse one.  Both live in ``tests/fixtures/mesh`` and are generated by
``scripts/generate_mesh_fixtures.py``, so these measurements run everywhere —
nothing here reaches for a scan outside the repository.

``reproducible=True`` is on for every emission so that the only thing standing
between two runs of the same job is geometry, not a clock.
"""

from __future__ import annotations

import asyncio
import math
import re
from itertools import pairwise
from pathlib import Path

import httpx
import pytest
import shapely
from shapely.geometry import LineString, MultiLineString, Polygon
from test_pineapple_crown_sliver import _body_print_moves, _gcode_raster_angle

from clayline.webui.app import create_app

ORIGIN = {"origin": "http://testserver", "host": "testserver"}
MESH = Path(__file__).parent / "fixtures" / "mesh"

# The house setting these fixtures were drawn for: a 4 mm bead, 2 mm layers.
# The lid is 14 mm tall (6 printed layers); the tumbler is 80 mm (39).
NOZZLE = 4.0
LAYER_HEIGHT = 2.0
BEAD_WIDTH = 4.0
LID = ("teapot-lid.obj", 14.0)
TUMBLER = ("tall-tumbler.obj", 80.0)

# The hollow route's own body bytes, captured by emitting these two fixtures
# from a worktree of ``3bfd838`` — the commit before the first line of the
# interior series landed.  ``body_sha256`` is the emitter's own digest of the
# motion body, so it moves when a single coordinate moves and does not move
# when the header's clock does.  Interior defaults to hollow: if either of
# these changes, a hollow vessel started paying for a feature it did not ask
# for.
PRE_SERIES_HOLLOW_BODY_SHA256 = {
    "teapot-lid.obj": "52a089b56d03188e1fedd177e85833e2545dffe37831ce280f36fa7550cd2a90",
    "tall-tumbler.obj": "7844fc72dc293a9c8b189a1ab8e84a730e46ee28fcdf4b96f45f0b3f803dd3ba",
}

_EMISSIONS: dict[tuple, tuple[dict, dict, str]] = {}


async def _interior_route(
    fixture: str,
    fit_height: float,
    settings: tuple[tuple[str, object], ...],
) -> tuple[dict, dict, str]:
    """Drive one fixture through the desktop route the app itself calls."""

    app = create_app()
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app),
        base_url="http://testserver",
        timeout=120,
    ) as client:
        mesh = await client.post(
            f"/api/weave/mesh?filename={fixture}&up=z&fit_height={fit_height}",
            content=(MESH / fixture).read_bytes(),
            headers={**ORIGIN, "content-type": "application/octet-stream"},
        )
        assert mesh.status_code == 200, mesh.text
        sliced = await client.post(
            "/api/weave/slice",
            json={
                "mesh_id": mesh.json()["mesh_id"],
                "nozzle": NOZZLE,
                "layer_height": LAYER_HEIGHT,
                "first_layer_height": LAYER_HEIGHT,
            },
            headers=ORIGIN,
        )
        assert sliced.status_code == 200, sliced.text
        slice_payload = sliced.json()
        print_range = slice_payload["print_range"]
        request = {
            "slice_id": slice_payload["slice_id"],
            "quality": "settle",
            "wave": "sine",
            "amplitude": 0.6,
            "wavelength": 12.0,
            "twist": 0.0,
            "z_blend": False,
            "level_rim": False,
            "island_range_auto": True,
            "reproducible": True,
            "layer_range": [print_range["from"], print_range["to"]],
        }
        request.update(dict(settings))
        modulated = await client.post("/api/weave/modulate", json=request, headers=ORIGIN)
        assert modulated.status_code == 200, modulated.text
        modulated_payload = modulated.json()
        finalized = await client.post(
            "/api/weave/finalize",
            json={"prepared_id": modulated_payload["prepared_id"]},
            headers=ORIGIN,
        )
        # Finalize is where the independent lint runs, and the route refuses
        # rather than hand back a file it will not stand behind.  A 200 here is
        # the lint verdict, not a formality.
        assert finalized.status_code == 200, finalized.text
        gcode = await client.get(
            f"/api/weave/result/{finalized.json()['result_id']}/gcode",
            headers=ORIGIN,
        )
        assert gcode.status_code == 200
        return slice_payload, modulated_payload, gcode.text


def _emit(form: tuple[str, float], **settings: object) -> tuple[dict, dict, str]:
    """Emit one job once, and hand the same bytes to every test that asks."""

    fixture, fit_height = form
    key = (fixture, fit_height, tuple(sorted(settings.items())))
    if key not in _EMISSIONS:
        _EMISSIONS[key] = asyncio.run(
            _interior_route(fixture, fit_height, tuple(sorted(settings.items())))
        )
    return _EMISSIONS[key]


# --- reading the emitted file -------------------------------------------------
#
# Print moves are parsed by ``test_pineapple_crown_sliver._body_print_moves``,
# imported rather than restated.  Travels are a different question that parser
# was never asked, so they get their own line matcher here — one that reads the
# same ``kind=`` token off the same trailing comment.

_TRAVEL_MOVE = re.compile(r"^G0 .*; clayline kind=travel\S* .* layer=(?P<layer>\d+) ")
_INTERIOR_NOTE = re.compile(
    r"^interior (?P<layer>\d+) of (?P<layers>\d+) · island "
    r"(?P<island>\d+) of (?P<islands>\d+)$"
)


def _header_number(gcode: str, key: str) -> float:
    match = re.search(rf"^; stats\.{re.escape(key)}=(\S+)$", gcode, re.MULTILINE)
    assert match is not None, f"missing stats.{key}"
    return float(match.group(1))


def _header_text(gcode: str, key: str) -> str:
    match = re.search(rf"^; {re.escape(key)}=(\S+)$", gcode, re.MULTILINE)
    assert match is not None, f"missing {key}"
    return match.group(1)


def _is_fill(move: dict[str, object]) -> bool:
    return str(move["note"]).startswith("interior ")


def _is_wall(move: dict[str, object]) -> bool:
    return str(move["note"]).endswith("wall")


def _printed_layers(moves: list[dict[str, object]]) -> list[int]:
    return sorted({int(move["layer"]) for move in moves})


def _travel_lines(gcode: str) -> list[tuple[int, int]]:
    """``(line number, layer)`` for every travel move in the body."""

    return [
        (number, int(match.group("layer")))
        for number, line in enumerate(gcode.splitlines(), start=1)
        if (match := _TRAVEL_MOVE.match(line)) is not None
    ]


def _travel_groups(gcode: str) -> dict[int, int]:
    """Count each layer's travels, a lift-traverse-approach set counting once."""

    travel_layer = dict(_travel_lines(gcode))
    printed = {int(move["line"]) for move in _body_print_moves(gcode)}
    counts: dict[int, int] = {}
    previous_was_travel = False
    for number in sorted(travel_layer.keys() | printed):
        travelling = number in travel_layer
        if travelling and not previous_was_travel:
            layer = travel_layer[number]
            counts[layer] = counts.get(layer, 0) + 1
        previous_was_travel = travelling
    return counts


def _runs(moves: list[dict[str, object]], gcode: str, layer: int) -> list[list[dict[str, object]]]:
    """One layer's deposition, split wherever the nozzle lifted and travelled."""

    travel_lines = {number for number, _layer in _travel_lines(gcode)}
    runs: list[list[dict[str, object]]] = []
    current: list[dict[str, object]] = []
    previous_line = None
    for move in moves:
        if int(move["layer"]) != layer:
            continue
        line = int(move["line"])
        if previous_line is not None and any(
            previous_line < travel < line for travel in travel_lines
        ):
            runs.append(current)
            current = []
        current.append(move)
        previous_line = line
    if current:
        runs.append(current)
    return runs


def _layer_parts(
    moves: list[dict[str, object]], gcode: str, layer: int
) -> tuple[list[list[dict[str, object]]], list[list[dict[str, object]]]]:
    """Split each of a layer's runs at its wall seam, into fill and wall.

    A welded run is the layer's fill followed by its wall ring, so the seam is
    the run's first wall-labelled move and everything before it is fill.  The
    flow ramp at the head of a run and the end-early taper at its tail carry
    notes of their own; both are kept on whichever side of the seam they fall,
    because the nozzle went there.  Dropping them would hand every measurement
    here a path the machine never followed.
    """

    fills: list[list[dict[str, object]]] = []
    walls: list[list[dict[str, object]]] = []
    for run in _runs(moves, gcode, layer):
        seam = next((index for index, move in enumerate(run) if _is_wall(move)), len(run))
        head = run[:seam]
        if any(_is_fill(move) for move in head):
            fills.append(head)
        if seam < len(run):
            walls.append(run[seam:])
    return fills, walls


def _fill_runs(
    moves: list[dict[str, object]], gcode: str, layer: int
) -> list[list[dict[str, object]]]:
    return _layer_parts(moves, gcode, layer)[0]


def _is_weld(move: dict[str, object]) -> bool:
    return str(move["note"]).endswith(" weld")


def _weld_paths(moves: list[dict[str, object]], gcode: str) -> dict[int, LineString]:
    """The bead that joins each layer's last rib to that layer's wall seam.

    Read as the machine drove it: from the last point before the weld notes
    start, through them, to the first wall point after them.  Taking only the
    weld-noted moves would drop the step onto the seam, which is the half bead
    that does the welding.
    """

    paths: dict[int, LineString] = {}
    for layer in _printed_layers(moves):
        run = [move for move in moves if int(move["layer"]) == layer]
        first = next((index for index, move in enumerate(run) if _is_weld(move)), None)
        if first is None:
            continue
        last = max(index for index, move in enumerate(run) if _is_weld(move))
        span = run[first - 1 : last + 2]
        paths[layer] = LineString([(float(m["x"]), float(m["y"])) for m in span])
    return paths


def _fill_points(
    moves: list[dict[str, object]], gcode: str, layer: int
) -> list[list[tuple[float, float]]]:
    return [
        [(float(move["x"]), float(move["y"])) for move in run]
        for run in _fill_runs(moves, gcode, layer)
    ]


def _wall_polygon(moves: list[dict[str, object]], gcode: str, layer: int) -> Polygon:
    walls = _layer_parts(moves, gcode, layer)[1]
    assert len(walls) == 1, f"layer {layer} printed {len(walls)} wall rings, not one"
    ring = [(float(move["x"]), float(move["y"])) for move in walls[0]]
    assert len(ring) > 3, f"layer {layer} emitted no wall ring to measure fill against"
    return Polygon(ring)


def _connectors(moves: list[dict[str, object]], gcode: str, layer: int) -> list[LineString]:
    """The step from a welded run's last fill point onto its wall seam.

    :func:`_layer_parts` splits a welded run in two, and the bead BETWEEN the
    halves belongs to neither of the LineStrings it hands back.  That bead is
    real: the nozzle drove it extruding and a paste machine cannot take it back.

    It matters most where it is the whole weld.  A weld of more than two points
    leaves weld-noted moves of its own, which fall on the fill side of the split
    and are walked with the rest of the fill — all but this last step onto the
    seam, which is the half bead that does the welding.  A TWO-POINT weld leaves
    no move of its own at ALL, because the sequencer splices only a route's
    middle into the fill path; the fill's last point is joined straight to the
    wall's first, and the entire weld lives in this gap.  Read off the emitted
    file either way, so this file keeps measuring the machine's own path rather
    than the one the builder's labels describe.
    """

    connectors: list[LineString] = []
    for run in _runs(moves, gcode, layer):
        seam = next((index for index, move in enumerate(run) if _is_wall(move)), len(run))
        if seam == 0 or seam >= len(run):
            continue
        head = run[:seam]
        if not any(_is_fill(move) for move in head):
            continue
        step = LineString(
            [
                (float(head[-1]["x"]), float(head[-1]["y"])),
                (float(run[seam]["x"]), float(run[seam]["y"])),
            ]
        )
        if step.length > 0.0:
            connectors.append(step)
    return connectors


def _deposited(moves: list[dict[str, object]], gcode: str, layer: int) -> list[LineString]:
    """Every extruding path of one layer, the connector included.

    This is what the layer put down, in the order the nozzle put it down: the
    fill runs, the step each welded run takes onto its wall seam, and the wall
    rings.  Used on both sides of a support measure — as the clay below, and as
    the deposition above being sampled — so neither side can quietly leave out
    a bead the other counts.
    """

    fills, walls = _layer_parts(moves, gcode, layer)
    paths = [
        LineString([(float(m["x"]), float(m["y"])) for m in run])
        for run in (*fills, *walls)
        if len(run) > 1
    ]
    paths.extend(_connectors(moves, gcode, layer))
    return paths


def _clay_below(
    moves: list[dict[str, object]], gcode: str, layer: int
) -> shapely.geometry.base.BaseGeometry:
    """Everything one layer put down that the layer above can land on.

    Ribs, the weld's step onto the seam, and wall: a rib that lands on the wall
    below it is supported, and a support measure that ignored the wall would
    call the outermost rib of every layer unsupported.  The weld is clay at that
    layer's own Z exactly as the two paths it joins, so it holds a rib up
    exactly as they do.
    """

    return shapely.union_all(_deposited(moves, gcode, layer))


def _island_count(moves: list[dict[str, object]], layer: int) -> int:
    islands = {
        int(match.group("islands"))
        for move in moves
        if int(move["layer"]) == layer and (match := _INTERIOR_NOTE.match(str(move["note"])))
    }
    assert len(islands) == 1, f"layer {layer} disagrees with itself about its island count"
    return islands.pop()


def _turns(points: list[tuple[float, float]]) -> float:
    """How many times a path circles its own centroid.

    A boundary spiral winds inward ring after ring, so this counts the rings.
    A serpentine raster sweeps back and forth across the same region and never
    completes a turn.  That is the difference between the two, stated as a
    number the emitted coordinates can answer.
    """

    centre_x = sum(x for x, _ in points) / len(points)
    centre_y = sum(y for _, y in points) / len(points)
    total = 0.0
    previous = None
    for x, y in points:
        angle = math.atan2(y - centre_y, x - centre_x)
        if previous is not None:
            step = (angle - previous + math.pi) % (2.0 * math.pi) - math.pi
            total += step
        previous = angle
    return abs(total) / (2.0 * math.pi)


def _rib_offsets(
    points: list[tuple[float, float]],
    *,
    angle_degrees: float,
    minimum_length: float = 6.0,
) -> dict[float, tuple[float, float]]:
    """Where a layer's ribs sit in the raster's own rotated frame.

    The infill grid is anchored at ``0.0`` in the bed frame rotated by the fill
    angle about ``(0, 0)``, so a rib's offset in that frame is the one number
    that says whether it landed on the rib below it.  Returns offset -> the
    span the rib covers along its own direction, so two layers' ribs can be
    checked for overlap and not merely for alignment.
    """

    radians = math.radians(-angle_degrees)
    cosine, sine = math.cos(radians), math.sin(radians)
    spans: dict[float, tuple[float, float]] = {}
    for (x0, y0), (x1, y1) in pairwise(points):
        if math.hypot(x1 - x0, y1 - y0) < minimum_length:
            continue
        u0, v0 = x0 * cosine - y0 * sine, x0 * sine + y0 * cosine
        u1, v1 = x1 * cosine - y1 * sine, x1 * sine + y1 * cosine
        if abs(v1 - v0) > 0.35:
            continue
        offset = round(0.5 * (v0 + v1), 3)
        low, high = min(u0, u1), max(u0, u1)
        if offset in spans:
            low = min(low, spans[offset][0])
            high = max(high, spans[offset][1])
        spans[offset] = (low, high)
    return spans


def _warning_layers(payload: dict, code: str, phrase: str | None = None) -> set[int]:
    """The artist-facing layers a warning code names, read off the response."""

    named: set[int] = set()
    for warning in payload.get("warnings", ()):
        if warning["code"] != code:
            continue
        if phrase is not None and phrase not in warning["message"]:
            continue
        span = re.search(r"span=(\d+)-(\d+)", warning["message"])
        assert span is not None, warning["message"]
        named.update(range(int(span.group(1)), int(span.group(2)) + 1))
    return named


# --- the solid interior, on the lid -------------------------------------------


def _solid_lid() -> tuple[dict, dict, str]:
    return _emit(LID, interior="solid", solid_pattern="crossing")


def test_solid_lid_lays_fill_then_wall_at_one_z_with_no_travel_between_them() -> None:
    _sliced, _modulated, gcode = _solid_lid()
    moves = _body_print_moves(gcode)
    layers = _printed_layers(moves)
    travels = {number for number, _layer in _travel_lines(gcode)}

    assert layers == list(range(6))
    for layer in layers:
        fill = [move for move in moves if int(move["layer"]) == layer and _is_fill(move)]
        wall = [move for move in moves if int(move["layer"]) == layer and _is_wall(move)]
        assert fill and wall, f"layer {layer} is missing its fill or its wall"

        # One Z for the whole layer: the fill is not a lifted second pass.
        heights = {float(move["z"]) for move in (*fill, *wall)}
        assert heights == {LAYER_HEIGHT * (layer + 1)}

        # Fill first, and the wall seam welded straight onto the last fill
        # point — no lift, no traverse, no approach in between.
        last_fill = max(int(move["line"]) for move in fill)
        first_wall = min(int(move["line"]) for move in wall)
        assert last_fill < first_wall
        assert not any(last_fill < travel < first_wall for travel in travels), (
            f"layer {layer} travelled between its last fill point and its wall seam"
        )


def test_solid_lid_opens_and_closes_on_a_boundary_spiral_and_crosses_in_between() -> None:
    _sliced, _modulated, gcode = _solid_lid()
    moves = _body_print_moves(gcode)
    layers = _printed_layers(moves)

    turns = {
        layer: _turns([point for run in _fill_points(moves, gcode, layer) for point in run])
        for layer in layers
    }
    # The bed face and the show face are boundary spirals: each winds inward
    # ring after ring around its own centroid.
    assert turns[layers[0]] > 3.0
    assert turns[layers[-1]] > 3.0
    # Everything between them is a serpentine raster, which never gets around.
    for layer in layers[1:-1]:
        assert turns[layer] < 1.0, f"layer {layer} circles like a spiral, not a raster"

    angles = {
        layer: _gcode_raster_angle(
            [move for run in _fill_runs(moves, gcode, layer) for move in run]
        )
        for layer in layers[1:-1]
    }
    assert angles == {1: 45.0, 2: 135.0, 3: 45.0, 4: 135.0}
    for lower, upper in pairwise(layers[1:-1]):
        assert abs(angles[upper] - angles[lower]) == pytest.approx(90.0, abs=4.0)


def test_solid_lid_fill_stays_inside_the_modulated_wall_and_welds_to_it() -> None:
    _sliced, _modulated, gcode = _solid_lid()
    moves = _body_print_moves(gcode)

    for layer in _printed_layers(moves):
        polygon = _wall_polygon(moves, gcode, layer)
        assert polygon.is_valid, f"layer {layer} emitted a wall ring that crosses itself"
        runs = _fill_points(moves, gcode, layer)
        assert runs
        for run in runs:
            assert polygon.covers(LineString(run)), (
                f"layer {layer} deposits fill outside the wall it prints"
            )
        # The outermost fill pass sits half a bead inside the wall's own
        # centreline, so a 4 mm fill bead and a 4 mm wall bead share 2 mm of
        # clay.  That overlap is the weld; measure it rather than trust it.
        boundary = polygon.exterior
        insets = [boundary.distance(shapely.Point(point)) for run in runs for point in run]
        assert min(insets) == pytest.approx(BEAD_WIDTH / 2.0, abs=0.15)


def test_solid_lid_lifts_no_more_than_once_per_island_per_layer() -> None:
    """2026-08-04: the lid prints as ONE line now, so most layers lift not at
    all — ``travels`` has no entry for them at all rather than an entry of one.

    Was ``travels[layer] <= islands + forced_splits`` for every layer, written
    when a filled form lifted once a layer by construction.  A layer that never
    lifts is the improvement, not a missing measurement (Pete 2026-08-04).
    """

    _sliced, _modulated, gcode = _solid_lid()
    moves = _body_print_moves(gcode)
    travels = _travel_groups(gcode)

    for layer in _printed_layers(moves):
        islands = _island_count(moves, layer)
        runs = _fill_runs(moves, gcode, layer)
        forced_splits = len(runs) - islands
        assert islands == 1
        assert forced_splits == 0, "the lid's raster proofs forced a split that used to not exist"
        assert travels.get(layer, 0) <= islands + forced_splits


def test_solid_lid_survives_the_route_lint_and_counts_its_own_strokes() -> None:
    _sliced, _modulated, gcode = _solid_lid()

    # The route refuses on a lint failure, so a finished file is the verdict.
    assert "; CLAYLINE_BODY_END" in gcode
    assert _header_number(gcode, "stroke_count") == gcode.count("CLAYLINE_STROKE_BEGIN")
    # Was six — one welded run of fill-then-wall per layer, each its own stroke.
    # 2026-08-04: one.  The lid climbs at its seam while depositing and never
    # leaves the clay, so the whole form is a single unbroken stroke, which is
    # the point of the thread (Pete 2026-08-04).
    assert _header_number(gcode, "stroke_count") == 1


# --- the sparse interior, on the tumbler --------------------------------------


def _sparse_tumbler() -> tuple[dict, dict, str]:
    return _emit(TUMBLER, interior="infill", infill_spacing_beads=3.0)


def _ramped_tumbler() -> tuple[dict, dict, str]:
    return _emit(
        TUMBLER,
        interior="infill",
        infill_spacing_beads=4.0,
        infill_base_layers=2,
        infill_cap_layers=2,
        infill_ramp_layers=3,
    )


def test_infill_tumbler_drift_is_bounded_exactly_where_the_warning_is_silent() -> None:
    _sliced, modulated, gcode = _sparse_tumbler()
    moves = _body_print_moves(gcode)
    layers = _printed_layers(moves)
    assert layers == list(range(39))

    measured: dict[int, float] = {}
    for below, above in pairwise(layers):
        beneath = _clay_below(moves, gcode, below)
        # Sampled along the upper path, not just at its corners: a rib can walk
        # off its support between two vertices 50 mm apart.  A quarter bead is
        # the interval the drift check itself walks.
        # The fill runs AND the step each welded run takes onto its wall seam.
        # That step is deposition the layer above's own support measure has to
        # answer for, and on a two-point weld it is the entire weld — spliced
        # into no path, noted by no move, and invisible to a helper that reads
        # only the fill runs.
        overhead = shapely.points(
            shapely.get_coordinates(
                shapely.segmentize(
                    MultiLineString(
                        [
                            *(run for run in _fill_points(moves, gcode, above) if len(run) > 1),
                            *_connectors(moves, gcode, above),
                        ]
                    ),
                    BEAD_WIDTH * 0.25,
                )
            )
        )
        measured[above] = float(shapely.distance(beneath, overhead).max())

    drifting = {layer + 1 for layer, distance in measured.items() if distance > BEAD_WIDTH / 2.0}
    named = _warning_layers(modulated, "infill_drift")

    # The warning names the bands where fill lands more than half a bead from
    # the clay below it, and nowhere else.
    assert drifting == named == {4, 8, 33}
    # And it names the millimetre it measured.  Reading the same number off the
    # file is what makes the sentence checkable by the potter it is written for.
    assert [round(measured[layer - 1], 5) for layer in sorted(named)] == [6.06816, 2.59483, 2.68536]
    # Everywhere it is silent, the overlay really is within half a bead — and
    # not marginally so: the worst silent pair spends a third of the budget.
    silent = [distance for layer, distance in measured.items() if layer + 1 not in named]
    assert max(silent) <= BEAD_WIDTH / 2.0
    # THE WHOLE WELD IS IN THIS MEASURE, its last step included.  The weld-noted
    # moves carry the fill's own note and were always walked here; the STEP onto
    # the wall seam belongs to no run at all — it is the boundary between the two
    # halves the seam split makes — and it is the half bead that does the
    # welding.  Adding it moved the worst silent pair from layer 12's 0.76006 mm
    # to layer 39's 1.00381 mm, which is that layer's connector alone: its own
    # fill reaches only 0.29065 mm.  Still a quarter of the budget clear of the
    # 2.0 mm half bead, and it moved neither the layers the warning names nor
    # the millimetres it names them with.
    assert max(silent) == pytest.approx(1.00381, abs=1e-4)
    assert max(silent) < BEAD_WIDTH / 2.0


def test_infill_tumbler_stacks_one_rib_through_the_whole_form() -> None:
    _sliced, _modulated, gcode = _sparse_tumbler()
    moves = _body_print_moves(gcode)
    layers = _printed_layers(moves)

    spans_by_layer = {
        layer: _rib_offsets(
            [point for run in _fill_points(moves, gcode, layer) for point in run],
            angle_degrees=45.0,
        )
        for layer in layers
    }
    # Ribs land on the anchored grid, not on a set centred in each layer's own
    # bounds: every offset is an exact multiple of the 12 mm spacing even as
    # the belly swells and settles.
    for layer, spans in spans_by_layer.items():
        assert spans, f"layer {layer} deposited no rib to stack on"
        for offset in spans:
            assert offset == pytest.approx(round(offset / 12.0) * 12.0, abs=1e-6), layer

    longest = 0
    for offset in {offset for spans in spans_by_layer.values() for offset in spans}:
        streak = 0
        previous: tuple[float, float] | None = None
        for layer in layers:
            span = spans_by_layer[layer].get(offset)
            overlapping = span is not None and (
                previous is None or min(span[1], previous[1]) > max(span[0], previous[0])
            )
            streak = streak + 1 if overlapping else 0
            longest = max(longest, streak)
            previous = span
    # A rib is a wall the artist cannot see: it has to be continuous clay, not
    # a stack of coincidences.
    assert longest >= 30
    assert longest == 39


def test_infill_tumbler_ramp_halves_its_spacing_and_leaves_the_ribs_below_alone() -> None:
    _sliced, modulated, gcode = _ramped_tumbler()
    moves = _body_print_moves(gcode)
    layers = _printed_layers(moves)

    spans_by_layer = {
        layer: _rib_offsets(
            [point for run in _fill_points(moves, gcode, layer) for point in run],
            angle_degrees=45.0,
        )
        for layer in layers
    }

    def spacing(layer: int) -> float:
        offsets = sorted(spans_by_layer[layer])
        assert len(offsets) > 1, layer
        return min(round(upper - lower, 3) for lower, upper in pairwise(offsets))

    # The sparse body runs at 4 beads; the ramp halves once per layer until it
    # reaches the dense cap's own spacing, and stops rather than overlapping.
    body, first_ramp, second_ramp, dense_cap = 34, 35, 36, 37
    assert spacing(body) == pytest.approx(4.0 * BEAD_WIDTH)
    assert spacing(first_ramp) == pytest.approx(2.0 * BEAD_WIDTH)
    assert spacing(second_ramp) == pytest.approx(1.0 * BEAD_WIDTH)
    assert spacing(dense_cap) == pytest.approx(BEAD_WIDTH * 0.8, abs=1e-6)
    for lower, upper in pairwise((body, first_ramp, second_ramp)):
        assert spacing(upper) == pytest.approx(spacing(lower) / 2.0)

    # Pre-ramp ribs are where they were.  A ramp adds lines midway; it never
    # slides the ones already carrying the form.
    for lower, upper in pairwise((body, first_ramp, second_ramp)):
        assert set(spans_by_layer[lower]) <= set(spans_by_layer[upper]), (
            f"layer {upper} moved the ribs layer {lower} laid down"
        )

    # Every tightening step is a bead asked to bridge the clear gap the spacing
    # below leaves it — the spacing, less the one bead its two neighbours
    # contribute.  Over two bead widths and the artist hears about it.
    bridges = {
        upper: spacing(lower) - BEAD_WIDTH
        for lower, upper in pairwise((body, first_ramp, second_ramp, dense_cap))
        if spacing(upper) < spacing(lower)
    }
    assert bridges == {
        first_ramp: pytest.approx(3.0 * BEAD_WIDTH),
        second_ramp: pytest.approx(1.0 * BEAD_WIDTH),
        dense_cap: pytest.approx(0.0, abs=1e-6),
    }
    named = _warning_layers(modulated, "infill_ramp_bridge", phrase="of open air")
    assert (
        {layer + 1 for layer, gap in bridges.items() if gap > 2.0 * BEAD_WIDTH}
        == named
        == {first_ramp + 1}
    )


def test_infill_tumbler_at_three_beads_bridges_nothing_it_does_not_announce() -> None:
    _sliced, modulated, gcode = _emit(
        TUMBLER,
        interior="infill",
        infill_spacing_beads=3.0,
        infill_base_layers=2,
        infill_cap_layers=2,
        infill_ramp_layers=3,
    )
    moves = _body_print_moves(gcode)
    spans_by_layer = {
        layer: _rib_offsets(
            [point for run in _fill_points(moves, gcode, layer) for point in run],
            angle_degrees=45.0,
        )
        for layer in _printed_layers(moves)
    }

    def spacing(layer: int) -> float:
        offsets = sorted(spans_by_layer[layer])
        assert len(offsets) > 1, layer
        return min(round(upper - lower, 3) for lower, upper in pairwise(offsets))

    # 3 beads of spacing puts the first halving's bridge exactly on the limit,
    # which is where the shipped default was chosen to sit.
    assert spacing(35) == pytest.approx(3.0 * BEAD_WIDTH)
    assert spacing(36) == pytest.approx(1.5 * BEAD_WIDTH)
    assert spacing(35) - BEAD_WIDTH == pytest.approx(2.0 * BEAD_WIDTH)
    assert _warning_layers(modulated, "infill_ramp_bridge", phrase="of open air") == set()


def test_infill_tumbler_lifts_once_a_layer_and_no_more() -> None:
    """Item 3's accept criterion, met on the emitted file.

    The criterion is "travel count per layer <= island count + segment splits
    the raster proofs force".  This form has one island a layer and no forced
    split, so the whole budget is one lift — the hop up from the layer below —
    and the ribs, their turnarounds, the weld and the wall spend nothing.

    An earlier round spent two, having found that a straight bead from the last
    rib to the wall seam crossed the open lattice (887 mm of it over a cone
    print) and chosen a travel instead.  The straight bead was the mistake, not
    the weld: the route that stays over clay rides the region's inset boundary
    and steps half a bead out onto the wall.  Clay does not stop and start —
    there is no retraction on a paste extruder — so the budget is the thing
    that holds and the route is what has to be right.
    """

    _sliced, _modulated, gcode = _sparse_tumbler()
    moves = _body_print_moves(gcode)
    travels = _travel_groups(gcode)
    layers = _printed_layers(moves)

    for layer in layers:
        islands = _island_count(moves, layer)
        forced_splits = len(_fill_runs(moves, gcode, layer)) - islands
        assert islands == 1
        assert forced_splits == 0
        assert travels[layer] == islands + forced_splits
        assert travels[layer] == 1

    # Said the other way round, because this is the sentence Pete measured the
    # feature by: over the whole body the nozzle leaves the clay once per
    # printed layer and not once more.  The first layer's own travel is the
    # approach from the park position, which every route pays.
    assert sum(travels.values()) == len(layers)


def test_the_rib_its_weld_and_its_wall_are_one_deposition_run() -> None:
    """One island's layer is a single unbroken run, and the weld is inside it.

    A run is what lies between two lifts.  If the ribs and the wall are in the
    same run there is no travel between them, which is the whole claim; and the
    weld is findable in the file — it carries the fill's own note with ``weld``
    on the end — so its length can be measured rather than inferred.
    """

    _sliced, _modulated, gcode = _sparse_tumbler()
    moves = _body_print_moves(gcode)

    for layer in _printed_layers(moves):
        runs = _runs(moves, gcode, layer)
        assert len(runs) == 1, layer
        # Fill, then weld, then wall, in that order and with nothing between.
        # The prime ramp at the head of a run and the end-early taper at its
        # tail carry notes of their own and are the emitter's business, not
        # this measurement's.
        order = ("fill", "weld", "wall")
        kinds = [
            "weld" if _is_weld(move) else "wall" if _is_wall(move) else "fill"
            for move in runs[0]
            if _is_weld(move) or _is_wall(move) or _is_fill(move)
        ]
        assert set(kinds) == set(order), layer
        assert kinds == sorted(kinds, key=order.index), layer

    # The weld itself: from the last rib point through the weld moves onto the
    # wall seam, half a bead of step plus whatever ride the boundary needed.
    welds = _weld_paths(moves, gcode)
    assert len(welds) == len(_printed_layers(moves))
    for layer, path in welds.items():
        assert BEAD_WIDTH / 2.0 <= path.length <= BEAD_WIDTH, layer


def test_infill_tumbler_is_lighter_than_the_same_form_solid() -> None:
    _sliced, _modulated, sparse = _sparse_tumbler()
    _solid_sliced, _solid_modulated, solid = _emit(TUMBLER, interior="solid")

    sparse_mass = _header_number(sparse, "wet_weight_g")
    solid_mass = _header_number(solid, "wet_weight_g")
    hollow_mass = _header_number(_emit(TUMBLER, interior="hollow")[2], "wet_weight_g")

    # Ribs exist to carry a form without the drying mass of solid clay.  The
    # report has to show that, or the control is decorative.
    #
    # 237.274555 g before the ribs welded to their walls, and the 8.31 g between
    # the two numbers is worth naming because only a tenth of it is new bead.
    # The welds themselves add 88.4 mm of path.  The other 195 mm is path this
    # form was already driving under a PRIME RAMP: every deposition run starts
    # with 5 mm of ramping extrusion that lays less than a bead, and halving the
    # run count from 78 to 39 halves what that costs.  So most of the extra clay
    # is not clay that was added — it is clay that was being missed at every
    # restart, which is the ooze-and-blob the weld exists to stop.
    assert sparse_mass == pytest.approx(245.589324, abs=1e-4)
    assert solid_mass == pytest.approx(598.963563, abs=1e-4)
    assert hollow_mass == pytest.approx(108.481843, abs=1e-4)
    assert sparse_mass < 0.5 * solid_mass
    assert hollow_mass < sparse_mass < solid_mass
    assert "; CLAYLINE_BODY_END" in sparse


# --- the hollow route, unmoved ------------------------------------------------


@pytest.mark.parametrize("form", [LID, TUMBLER])
def test_hollow_is_byte_identical_whether_or_not_the_interior_is_named(
    form: tuple[str, float],
) -> None:
    _named_sliced, _named_modulated, named = _emit(form, interior="hollow")
    # No interior key at all: this request cannot see the settings the series
    # added, and it is the request every saved recipe from before the series
    # still sends.
    _bare_sliced, _bare_modulated, bare = _emit(form)

    assert named == bare
    assert "note=interior " not in bare
    assert _header_text(bare, "body_sha256") == PRE_SERIES_HOLLOW_BODY_SHA256[form[0]]
    assert _header_number(bare, "stroke_count") == 1
